# Writes the vulkan package's layout test from the package's own struct
# declarations: layout.cone, which prints the size and alignment of each
# struct in the package's src/ and the offset of each of its fields, and
# layout.inc, the same prints for layout.c, which holds the structs as C
# declares them. Run it after adding or changing a struct, then remake
# layout.out from C (layout.c says how), so that 'congo test' compares the
# Cone declarations with the C compiler's layout:
#
#   python layout.py
#
# A struct whose one field is 'h' (a handle) or 'raw' (storage standing in
# for a C union or an array of VkBool32s) has its size checked, not its
# fields.

import os
import re

here = os.path.dirname(os.path.abspath(__file__))
srcdir = os.path.join(here, '..', 'src')

# The package's files, in the order their structs are listed: every one of
# them, so a file added to src/ must be added here too
files = ['vulkan.cone', 'handles.cone', 'constants.cone', 'structs.cone',
         'commandstructs.cone', 'pipelinestructs.cone', 'fntypes.cone',
         'load.cone', 'functions.cone']
assert sorted(files) == sorted(f for f in os.listdir(srcdir) if f.endswith('.cone')), \
    'layout.py lists a different set of files than src/ holds'
src = ''
for name in files:
    with open(os.path.join(srcdir, name), encoding='utf-8') as f:
        src += f.read()

structs = []
for m in re.finditer(r'^pub struct (@opaque )?(\w+)\s*\{(.*?)\}', src, re.S | re.M):
    if not m.group(1):
        structs.append((m.group(2), re.findall(r'pub (\w+) ', m.group(3))))

c = ['/* Generated by layout.py from the package\'s src/: do not edit */']
cone = ['''// Generated by layout.py from the package's src/: do not edit. The size and
// alignment of every struct the vulkan package declares, and the offset of
// each of its fields, as Cone lays them out. layout.out is what layout.c
// prints for the same structs as C declares them, compiled by cl.exe, so a
// difference is a struct transcribed wrongly on one side or the other.

mod layout;

import stdio use *;
import libc;
import vulkan;

fn size(name &[]u8, n usize, a usize) {
  printStr(name); printStr(" size "); printUInt(u64.from(n)); printStr(" align "); printUInt(u64.from(a)); printStr("\\n");
}

fn o(name &[]u8, base usize, p *u8) {
  printStr(name); printStr(" "); printUInt(u64.from((p as usize) - base)); printStr("\\n");
}

fn main() i32 {''']

for name, fields in structs:
    t = 'vulkan.' + name
    line = f'  S({name});'
    cone.append(f'  size("{name}", mem.sizeof[{t}](), mem.alignof[{t}]());')
    if fields not in (['h'], ['raw']):
        cone.append('  {')
        cone.append(f'    imm raw = libc.calloc(1usize, mem.sizeof[{t}]()) as *{t};')
        cone.append(f'    mut v = mem.readRaw[{t}](raw);')
        cone.append('    imm b = &mut v as *u8 as usize;')
        for fld in fields:
            line += f' O({name}, {fld});'
            cone.append(f'    o("{name}.{fld}", b, &mut v.{fld} as *u8);')
        cone.append('    libc.free(raw as *u8);')
        cone.append('  }')
    c.append(line)
cone.append('  0;')
cone.append('}')

with open(os.path.join(here, 'layout.inc'), 'w', newline='\n') as f:
    f.write('\n'.join(c) + '\n')
with open(os.path.join(here, 'layout.cone'), 'w', newline='\n') as f:
    f.write('\n'.join(cone) + '\n')
print(len(structs), 'structs,', sum(len(fl) for _, fl in structs), 'fields')
