# Writes the sdl package's layout test from the package's own struct
# declarations: layout.cone, which prints the size and alignment of each
# struct in src/sdl.cone and the offset of each of its fields, and
# layout.inc, the same prints for layout.c, which includes SDL3's own
# headers. Run it after adding or changing a struct, then remake layout.out
# from C (layout.c says how), so that 'congo test' compares the Cone
# declarations with the C compiler's layout of SDL's:
#
#   python layout.py

import os
import re

here = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(here, '..', 'src', 'sdl.cone'), encoding='utf-8') as f:
    src = f.read()

# A Cone field whose C name differs, as C reaches it from the struct; None
# where C has no such field (the Event union's buffer, whose size is checked
# by the union's)
renamed = {
    ('Event', 'reserved'): 'common.reserved',
    ('Event', 'timestamp'): 'common.timestamp',
    ('Event', 'buffer'): None,
    ('KeyboardEvent', 'keymod'): 'mod',
}

structs = []
for m in re.finditer(r'^pub struct (@opaque )?(\w+)\s*\{(?:\}|(.*?)^\})', src, re.S | re.M):
    if not m.group(1) and m.group(3):
        fields = [f for f in re.findall(r'^\s*pub (\w+) ', m.group(3), re.M) if f != 'fn']
        structs.append((m.group(2), fields))

c = ['/* Generated by layout.py from the package\'s src/: do not edit */']
cone = ['''// Generated by layout.py from the package's src/: do not edit. The size and
// alignment of every struct the sdl package declares, and the offset of
// each of its fields, as Cone lays them out. layout.out is what layout.c
// prints for the same structs as SDL3's headers declare them, compiled by
// cl.exe, so a difference is a struct transcribed wrongly.

mod layout;

import stdio use *;
import libc;
import sdl;

fn size(name &[]u8, n usize, a usize) {
  printStr(name); printStr(" size "); printUInt(u64.from(n)); printStr(" align "); printUInt(u64.from(a)); printStr("\\n");
}

fn o(name &[]u8, base usize, p *u8) {
  printStr(name); printStr(" "); printUInt(u64.from((p as usize) - base)); printStr("\\n");
}

fn main() i32 {''']

nfields = 0
for name, fields in structs:
    t = 'sdl.' + name
    cone.append(f'  size("{name}", mem.sizeof[{t}](), mem.alignof[{t}]());')
    c.append(f'  S({name});')
    cone.append('  {')
    cone.append(f'    imm raw = libc.calloc(1usize, mem.sizeof[{t}]()) as *{t};')
    cone.append(f'    mut v = mem.readRaw[{t}](raw);')
    cone.append('    imm b = &mut v as *u8 as usize;')
    for fld in fields:
        cfld = renamed.get((name, fld), fld)
        if cfld is None:
            continue
        nfields += 1
        cone.append(f'    o("{name}.{fld}", b, &mut v.{fld} as *u8);')
        c.append(f'  O({name}, {cfld}, "{fld}");')
    cone.append('    libc.free(raw as *u8);')
    cone.append('  }')
cone.append('  0;')
cone.append('}')

with open(os.path.join(here, 'layout.inc'), 'w', newline='\n') as f:
    f.write('\n'.join(c) + '\n')
with open(os.path.join(here, 'layout.cone'), 'w', newline='\n') as f:
    f.write('\n'.join(cone) + '\n')
print(len(structs), 'structs,', nfields, 'fields')
