/** Generating a package's include file
 *
 * A library compile writes its package's include file: the Cone source a
 * program compiles against in place of the package's source. It is the root
 * module's own source text with what an importer does not need taken out -- a
 * body an importer does not expand, a declaration it cannot reach -- and
 * 'extern' written in where a body was; what the root reaches in one of its
 * submodules is written in a private, pruned nested module block holding just
 * that (compiler/c/doc/nodes/module.md, "Generating the include file").
 *
 * @file
 *
 * This source file is part of the Cone Programming Language C compiler
 * See Copyright Notice in conec.h
*/

#ifndef incfile_h
#define incfile_h

// The first words of every generated include file's banner, which is what
// tells a generated include file from a hand-written one where it is read
#define IncFileBanner "// Generated by conec: the include file of package "

// Generate the include file of the program's root module, after type check.
// Returns its text, NUL-terminated, with its length in '*lenp'; or NULL where
// something it would have to declare cannot be written, each reported
// (ErrorIncCheck).
char *incFileGenerate(ProgramNode *pgm, size_t *lenp);

// Whether a file's text is a generated include file: it opens with the
// generator's banner. Only such a file may hold a nested module block
int incFileIsGenerated(char *text);

#endif
